- name: Get Device OS
  hosts: all
  connection: local
  gather_facts: no

  tasks:
    - name: Retrieve facts from devices running Junos OS
      junos_facts:
        provider: "{{ credentials }}"

    - name: Print version
      debug:
        var: ansible_net_version
