- name: Get Device OS
  hosts: all
  connection: local
  gather_facts: no

  tasks:
    - name: Retrieve facts from devices running Junos OS
      junos_facts:
      register: version

    - name: Print version
      debug:
        msg: version.ansible_net_version
