- name: Get Device OS
  hosts: QFX
  connection: local
  gather_facts: no

  tasks:
    - name: Retrieve facts from devices running Junos OS
      junos_facts:
      register: version

    - debug:
        msg: "{{ansible_net_version}}"
