- name: Get Device OS
  hosts: all
  connection: local
  gather_facts: no

  tasks:
    - name: Retrieve facts from devices running Junos OS
      junos_facts:
      register: all

    - debug:
        msg: "{{all}}"
